---
dist: bionic
language: python

before_install:
  - scripts/travis.sh

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

before_script:
  - flake8 src/*.py
  - yamllint etc/*.yml

script:
  - python3 src/main.py
